name = "testpluto"
uuid = "292a2647-3466-47f3-9862-ecc2c84257e3"
authors = ["David Mawdsley <david.mawdsley@manchester.ac.uk>"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
